// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: temporal.proto

package workflowservice

import (
	"context"

	"github.com/hanyougame/live-proto/proto-gen-go/temporal/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseResponse                         = v1.BaseResponse
	BatchCancelWorkflowRequestV1         = v1.BatchCancelWorkflowRequestV1
	BatchCancelWorkflowResponseV1        = v1.BatchCancelWorkflowResponseV1
	BatchCancelWorkflowResponseV1_Result = v1.BatchCancelWorkflowResponseV1_Result
	BatchConfig                          = v1.BatchConfig
	BatchControlResult                   = v1.BatchControlResult
	BatchDeleteResult                    = v1.BatchDeleteResult
	BatchDeleteTarget                    = v1.BatchDeleteTarget
	BatchResult                          = v1.BatchResult
	BatchScheduleTaskRequestV1           = v1.BatchScheduleTaskRequestV1
	BatchScheduleTaskResponseV1          = v1.BatchScheduleTaskResponseV1
	BatchScheduleTaskResponseV1_Result   = v1.BatchScheduleTaskResponseV1_Result
	BatchTarget                          = v1.BatchTarget
	CancelWorkflowRequestV1              = v1.CancelWorkflowRequestV1
	CancelWorkflowResponseV1             = v1.CancelWorkflowResponseV1
	ControlOperationInfo                 = v1.ControlOperationInfo
	ControlOptions                       = v1.ControlOptions
	ControlWorkflowData                  = v1.ControlWorkflowData
	ControlWorkflowRequest               = v1.ControlWorkflowRequest
	ControlWorkflowResponse              = v1.ControlWorkflowResponse
	DelayOptions                         = v1.DelayOptions
	DeleteOptions                        = v1.DeleteOptions
	DeleteScheduleReqV1                  = v1.DeleteScheduleReqV1
	DeleteStatistics                     = v1.DeleteStatistics
	DeleteWorkflowData                   = v1.DeleteWorkflowData
	DeleteWorkflowRequest                = v1.DeleteWorkflowRequest
	DeleteWorkflowResponse               = v1.DeleteWorkflowResponse
	ExecutionConfig                      = v1.ExecutionConfig
	ExecutionInfo                        = v1.ExecutionInfo
	GetWorkflowExecutionRequestV1        = v1.GetWorkflowExecutionRequestV1
	GetWorkflowExecutionResponseV1       = v1.GetWorkflowExecutionResponseV1
	ListOptions                          = v1.ListOptions
	ListScheduleOptions                  = v1.ListScheduleOptions
	ListSchedulesData                    = v1.ListSchedulesData
	ListSchedulesRequest                 = v1.ListSchedulesRequest
	ListSchedulesResponse                = v1.ListSchedulesResponse
	ListSearchAttributesData             = v1.ListSearchAttributesData
	ListSearchAttributesRequest          = v1.ListSearchAttributesRequest
	ListSearchAttributesResponse         = v1.ListSearchAttributesResponse
	ListWorkflowsData                    = v1.ListWorkflowsData
	ListWorkflowsRequest                 = v1.ListWorkflowsRequest
	ListWorkflowsResponse                = v1.ListWorkflowsResponse
	ManageScheduleData                   = v1.ManageScheduleData
	ManageScheduleRequest                = v1.ManageScheduleRequest
	ManageScheduleResponse               = v1.ManageScheduleResponse
	PageRequest                          = v1.PageRequest
	PageResponse                         = v1.PageResponse
	QueryControlOperationData            = v1.QueryControlOperationData
	QueryControlOperationRequest         = v1.QueryControlOperationRequest
	QueryControlOperationResponse        = v1.QueryControlOperationResponse
	QueryDeleteResult                    = v1.QueryDeleteResult
	QueryDeleteTarget                    = v1.QueryDeleteTarget
	QueryOptions                         = v1.QueryOptions
	QueryScheduleRequest                 = v1.QueryScheduleRequest
	QueryScheduleResponse                = v1.QueryScheduleResponse
	QuerySearchAttributeUsageData        = v1.QuerySearchAttributeUsageData
	QuerySearchAttributeUsageRequest     = v1.QuerySearchAttributeUsageRequest
	QuerySearchAttributeUsageResponse    = v1.QuerySearchAttributeUsageResponse
	QueryWorkflowData                    = v1.QueryWorkflowData
	QueryWorkflowRequest                 = v1.QueryWorkflowRequest
	QueryWorkflowResponse                = v1.QueryWorkflowResponse
	QueryWorkflowStateData               = v1.QueryWorkflowStateData
	QueryWorkflowStateRequest            = v1.QueryWorkflowStateRequest
	QueryWorkflowStateResponse           = v1.QueryWorkflowStateResponse
	RegisterSearchAttributesData         = v1.RegisterSearchAttributesData
	RegisterSearchAttributesRequest      = v1.RegisterSearchAttributesRequest
	RegisterSearchAttributesResponse     = v1.RegisterSearchAttributesResponse
	RemoveSearchAttributesData           = v1.RemoveSearchAttributesData
	RemoveSearchAttributesRequest        = v1.RemoveSearchAttributesRequest
	RemoveSearchAttributesResponse       = v1.RemoveSearchAttributesResponse
	ReplaceWorkflowData                  = v1.ReplaceWorkflowData
	ReplaceWorkflowRequest               = v1.ReplaceWorkflowRequest
	ReplaceWorkflowResponse              = v1.ReplaceWorkflowResponse
	RetentionPolicy                      = v1.RetentionPolicy
	RetryPolicy                          = v1.RetryPolicy
	RetryPolicyOpt                       = v1.RetryPolicyOpt
	ScheduleCalendarSpec                 = v1.ScheduleCalendarSpec
	ScheduleInfo                         = v1.ScheduleInfo
	ScheduleOptions                      = v1.ScheduleOptions
	SchedulePolicy                       = v1.SchedulePolicy
	ScheduleRange                        = v1.ScheduleRange
	ScheduleResult                       = v1.ScheduleResult
	ScheduleSpec                         = v1.ScheduleSpec
	ScheduleSpecDesc                     = v1.ScheduleSpecDesc
	ScheduleTaskRequestV1                = v1.ScheduleTaskRequestV1
	ScheduleTaskResponseV1               = v1.ScheduleTaskResponseV1
	ScheduleWorkflowAction               = v1.ScheduleWorkflowAction
	SearchAttributeFilter                = v1.SearchAttributeFilter
	SearchAttributeInfo                  = v1.SearchAttributeInfo
	SearchAttributeRegistrationResult    = v1.SearchAttributeRegistrationResult
	SearchAttributeRemovalResult         = v1.SearchAttributeRemovalResult
	SearchAttributeStats                 = v1.SearchAttributeStats
	SearchAttributeUsage                 = v1.SearchAttributeUsage
	SearchAttributeValidation            = v1.SearchAttributeValidation
	SignalFlowRequest                    = v1.SignalFlowRequest
	SignalFlowResponse                   = v1.SignalFlowResponse
	SignalWithStartData                  = v1.SignalWithStartData
	SignalWithStartRequest               = v1.SignalWithStartRequest
	SignalWithStartResponse              = v1.SignalWithStartResponse
	SignalWorkflowData                   = v1.SignalWorkflowData
	SignalWorkflowRequestV1              = v1.SignalWorkflowRequestV1
	SignalWorkflowResponseV1             = v1.SignalWorkflowResponseV1
	SingleDeleteResult                   = v1.SingleDeleteResult
	SingleDeleteTarget                   = v1.SingleDeleteTarget
	SingleResult                         = v1.SingleResult
	StackFrame                           = v1.StackFrame
	StartFlowRequest                     = v1.StartFlowRequest
	StartFlowResponse                    = v1.StartFlowResponse
	StartWorkflowData                    = v1.StartWorkflowData
	StartWorkflowRequestV1               = v1.StartWorkflowRequestV1
	StartWorkflowResponseV1              = v1.StartWorkflowResponseV1
	StringList                           = v1.StringList
	TemporalReply                        = v1.TemporalReply
	TemporalReq                          = v1.TemporalReq
	UsageQueryOptions                    = v1.UsageQueryOptions
	UsageStats                           = v1.UsageStats
	ValidateSearchAttributesData         = v1.ValidateSearchAttributesData
	ValidateSearchAttributesRequest      = v1.ValidateSearchAttributesRequest
	ValidateSearchAttributesResponse     = v1.ValidateSearchAttributesResponse
	ValidationResult                     = v1.ValidationResult
	ValueDistribution                    = v1.ValueDistribution
	WorkflowAction                       = v1.WorkflowAction
	WorkflowEvent                        = v1.WorkflowEvent
	WorkflowHistory                      = v1.WorkflowHistory
	WorkflowInfo                         = v1.WorkflowInfo
	WorkflowItem                         = v1.WorkflowItem
	WorkflowOptions                      = v1.WorkflowOptions
	WorkflowOpts                         = v1.WorkflowOpts
	WorkflowStackTrace                   = v1.WorkflowStackTrace
	WorkflowStatus                       = v1.WorkflowStatus
	WorkflowTarget                       = v1.WorkflowTarget

	WorkflowService interface {
		// 启动工作流 (支持立即/延迟/调度/批量)
		StartWorkflow(ctx context.Context, in *StartFlowRequest, opts ...grpc.CallOption) (*StartFlowResponse, error)
		// 控制工作流 (取消/终止/暂停/恢复)
		ControlWorkflow(ctx context.Context, in *ControlWorkflowRequest, opts ...grpc.CallOption) (*ControlWorkflowResponse, error)
		// 查询控制操作状态
		QueryControlOperation(ctx context.Context, in *QueryControlOperationRequest, opts ...grpc.CallOption) (*QueryControlOperationResponse, error)
		// 查询工作流状态和历史
		QueryWorkflow(ctx context.Context, in *QueryWorkflowRequest, opts ...grpc.CallOption) (*QueryWorkflowResponse, error)
		// 列出工作流
		ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error)
		// 原子替换工作流
		ReplaceWorkflow(ctx context.Context, in *ReplaceWorkflowRequest, opts ...grpc.CallOption) (*ReplaceWorkflowResponse, error)
		// 删除工作流（新增）
		DeleteWorkflow(ctx context.Context, in *DeleteWorkflowRequest, opts ...grpc.CallOption) (*DeleteWorkflowResponse, error)
	}

	defaultWorkflowService struct {
		cli zrpc.Client
	}
)

func NewWorkflowService(cli zrpc.Client) WorkflowService {
	return &defaultWorkflowService{
		cli: cli,
	}
}

// 启动工作流 (支持立即/延迟/调度/批量)
func (m *defaultWorkflowService) StartWorkflow(ctx context.Context, in *StartFlowRequest, opts ...grpc.CallOption) (*StartFlowResponse, error) {
	client := v1.NewWorkflowServiceClient(m.cli.Conn())
	return client.StartWorkflow(ctx, in, opts...)
}

// 控制工作流 (取消/终止/暂停/恢复)
func (m *defaultWorkflowService) ControlWorkflow(ctx context.Context, in *ControlWorkflowRequest, opts ...grpc.CallOption) (*ControlWorkflowResponse, error) {
	client := v1.NewWorkflowServiceClient(m.cli.Conn())
	return client.ControlWorkflow(ctx, in, opts...)
}

// 查询控制操作状态
func (m *defaultWorkflowService) QueryControlOperation(ctx context.Context, in *QueryControlOperationRequest, opts ...grpc.CallOption) (*QueryControlOperationResponse, error) {
	client := v1.NewWorkflowServiceClient(m.cli.Conn())
	return client.QueryControlOperation(ctx, in, opts...)
}

// 查询工作流状态和历史
func (m *defaultWorkflowService) QueryWorkflow(ctx context.Context, in *QueryWorkflowRequest, opts ...grpc.CallOption) (*QueryWorkflowResponse, error) {
	client := v1.NewWorkflowServiceClient(m.cli.Conn())
	return client.QueryWorkflow(ctx, in, opts...)
}

// 列出工作流
func (m *defaultWorkflowService) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error) {
	client := v1.NewWorkflowServiceClient(m.cli.Conn())
	return client.ListWorkflows(ctx, in, opts...)
}

// 原子替换工作流
func (m *defaultWorkflowService) ReplaceWorkflow(ctx context.Context, in *ReplaceWorkflowRequest, opts ...grpc.CallOption) (*ReplaceWorkflowResponse, error) {
	client := v1.NewWorkflowServiceClient(m.cli.Conn())
	return client.ReplaceWorkflow(ctx, in, opts...)
}

// 删除工作流（新增）
func (m *defaultWorkflowService) DeleteWorkflow(ctx context.Context, in *DeleteWorkflowRequest, opts ...grpc.CallOption) (*DeleteWorkflowResponse, error) {
	client := v1.NewWorkflowServiceClient(m.cli.Conn())
	return client.DeleteWorkflow(ctx, in, opts...)
}
