// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: finance.proto

package livewithdrawrpcservice

import (
	"context"
	"github.com/hanyougame/live-proto/proto-gen-go/finance/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAuditReq                   = v1.AddAuditReq
	AddAuditResp                  = v1.AddAuditResp
	AddWithdrawLimitReq           = v1.AddWithdrawLimitReq
	AddWithdrawLimitResp          = v1.AddWithdrawLimitResp
	BalanceReq                    = v1.BalanceReq
	BalanceResp                   = v1.BalanceResp
	ExchangeRateReq               = v1.ExchangeRateReq
	ExchangeRateResp              = v1.ExchangeRateResp
	PayInReq                      = v1.PayInReq
	PayInResp                     = v1.PayInResp
	PayInStatusReq                = v1.PayInStatusReq
	PayInStatusResp               = v1.PayInStatusResp
	PayOutReq                     = v1.PayOutReq
	PayOutResp                    = v1.PayOutResp
	PayOutStatusReq               = v1.PayOutStatusReq
	PayOutStatusResp              = v1.PayOutStatusResp
	RechargeReq                   = v1.RechargeReq
	RechargeResp                  = v1.RechargeResp
	UpdateAuditAmountReq          = v1.UpdateAuditAmountReq
	UpdateAuditAmountResp         = v1.UpdateAuditAmountResp
	UpdateWithdrawLimitAmountReq  = v1.UpdateWithdrawLimitAmountReq
	UpdateWithdrawLimitAmountResp = v1.UpdateWithdrawLimitAmountResp
	WithdrawReq                   = v1.WithdrawReq
	WithdrawResp                  = v1.WithdrawResp

	LiveWithdrawRpcService interface {
		// 添加提现
		Withdraw(ctx context.Context, in *WithdrawReq, opts ...grpc.CallOption) (*WithdrawResp, error)
	}

	defaultLiveWithdrawRpcService struct {
		cli zrpc.Client
	}
)

func NewLiveWithdrawRpcService(cli zrpc.Client) LiveWithdrawRpcService {
	return &defaultLiveWithdrawRpcService{
		cli: cli,
	}
}

// 添加提现
func (m *defaultLiveWithdrawRpcService) Withdraw(ctx context.Context, in *WithdrawReq, opts ...grpc.CallOption) (*WithdrawResp, error) {
	client := v1.NewLiveWithdrawRpcServiceClient(m.cli.Conn())
	return client.Withdraw(ctx, in, opts...)
}
