// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: manage/v1/manage.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LiveManageRpcService_GetLegalTenderInfo_FullMethodName = "/manage.v1.LiveManageRpcService/GetLegalTenderInfo"
	LiveManageRpcService_GetCurrInfoById_FullMethodName    = "/manage.v1.LiveManageRpcService/GetCurrInfoById"
)

// LiveManageRpcServiceClient is the client API for LiveManageRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiveManageRpcServiceClient interface {
	// 获取法定货币信息
	GetLegalTenderInfo(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*CurrencyDetailReplyList, error)
	// 通过货币ID获取货币信息
	GetCurrInfoById(ctx context.Context, in *GetCurrInfoByIDReq, opts ...grpc.CallOption) (*CurrencyDetailReply, error)
}

type liveManageRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLiveManageRpcServiceClient(cc grpc.ClientConnInterface) LiveManageRpcServiceClient {
	return &liveManageRpcServiceClient{cc}
}

func (c *liveManageRpcServiceClient) GetLegalTenderInfo(ctx context.Context, in *ManageReq, opts ...grpc.CallOption) (*CurrencyDetailReplyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrencyDetailReplyList)
	err := c.cc.Invoke(ctx, LiveManageRpcService_GetLegalTenderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liveManageRpcServiceClient) GetCurrInfoById(ctx context.Context, in *GetCurrInfoByIDReq, opts ...grpc.CallOption) (*CurrencyDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrencyDetailReply)
	err := c.cc.Invoke(ctx, LiveManageRpcService_GetCurrInfoById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiveManageRpcServiceServer is the server API for LiveManageRpcService service.
// All implementations must embed UnimplementedLiveManageRpcServiceServer
// for forward compatibility.
type LiveManageRpcServiceServer interface {
	// 获取法定货币信息
	GetLegalTenderInfo(context.Context, *ManageReq) (*CurrencyDetailReplyList, error)
	// 通过货币ID获取货币信息
	GetCurrInfoById(context.Context, *GetCurrInfoByIDReq) (*CurrencyDetailReply, error)
	mustEmbedUnimplementedLiveManageRpcServiceServer()
}

// UnimplementedLiveManageRpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLiveManageRpcServiceServer struct{}

func (UnimplementedLiveManageRpcServiceServer) GetLegalTenderInfo(context.Context, *ManageReq) (*CurrencyDetailReplyList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLegalTenderInfo not implemented")
}
func (UnimplementedLiveManageRpcServiceServer) GetCurrInfoById(context.Context, *GetCurrInfoByIDReq) (*CurrencyDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrInfoById not implemented")
}
func (UnimplementedLiveManageRpcServiceServer) mustEmbedUnimplementedLiveManageRpcServiceServer() {}
func (UnimplementedLiveManageRpcServiceServer) testEmbeddedByValue()                              {}

// UnsafeLiveManageRpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiveManageRpcServiceServer will
// result in compilation errors.
type UnsafeLiveManageRpcServiceServer interface {
	mustEmbedUnimplementedLiveManageRpcServiceServer()
}

func RegisterLiveManageRpcServiceServer(s grpc.ServiceRegistrar, srv LiveManageRpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedLiveManageRpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LiveManageRpcService_ServiceDesc, srv)
}

func _LiveManageRpcService_GetLegalTenderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveManageRpcServiceServer).GetLegalTenderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiveManageRpcService_GetLegalTenderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveManageRpcServiceServer).GetLegalTenderInfo(ctx, req.(*ManageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiveManageRpcService_GetCurrInfoById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrInfoByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveManageRpcServiceServer).GetCurrInfoById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiveManageRpcService_GetCurrInfoById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveManageRpcServiceServer).GetCurrInfoById(ctx, req.(*GetCurrInfoByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LiveManageRpcService_ServiceDesc is the grpc.ServiceDesc for LiveManageRpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiveManageRpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manage.v1.LiveManageRpcService",
	HandlerType: (*LiveManageRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLegalTenderInfo",
			Handler:    _LiveManageRpcService_GetLegalTenderInfo_Handler,
		},
		{
			MethodName: "GetCurrInfoById",
			Handler:    _LiveManageRpcService_GetCurrInfoById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "manage/v1/manage.proto",
}
