// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: user.proto

package liveuserrpcservice

import (
	"context"

	"github.com/hanyougame/live-proto/proto-gen-go/user/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetInfoByUserTokenReq = v1.GetInfoByUserTokenReq
	GetUserBalanceReply   = v1.GetUserBalanceReply
	GetUserBalanceReq     = v1.GetUserBalanceReq
	GetUserInfoByIdReq    = v1.GetUserInfoByIdReq
	UserDetailsInfoReply  = v1.UserDetailsInfoReply
	UserWalletInfo        = v1.UserWalletInfo

	LiveUserRpcService interface {
		GetInfoByUserToken(ctx context.Context, in *GetInfoByUserTokenReq, opts ...grpc.CallOption) (*UserDetailsInfoReply, error)
		GetUserBalance(ctx context.Context, in *GetUserBalanceReq, opts ...grpc.CallOption) (*GetUserBalanceReply, error)
		GetUserInfoById(ctx context.Context, in *GetUserInfoByIdReq, opts ...grpc.CallOption) (*UserDetailsInfoReply, error)
	}

	defaultLiveUserRpcService struct {
		cli zrpc.Client
	}
)

func NewLiveUserRpcService(cli zrpc.Client) LiveUserRpcService {
	return &defaultLiveUserRpcService{
		cli: cli,
	}
}

func (m *defaultLiveUserRpcService) GetInfoByUserToken(ctx context.Context, in *GetInfoByUserTokenReq, opts ...grpc.CallOption) (*UserDetailsInfoReply, error) {
	client := v1.NewLiveUserRpcServiceClient(m.cli.Conn())
	return client.GetInfoByUserToken(ctx, in, opts...)
}

func (m *defaultLiveUserRpcService) GetUserBalance(ctx context.Context, in *GetUserBalanceReq, opts ...grpc.CallOption) (*GetUserBalanceReply, error) {
	client := v1.NewLiveUserRpcServiceClient(m.cli.Conn())
	return client.GetUserBalance(ctx, in, opts...)
}

func (m *defaultLiveUserRpcService) GetUserInfoById(ctx context.Context, in *GetUserInfoByIdReq, opts ...grpc.CallOption) (*UserDetailsInfoReply, error) {
	client := v1.NewLiveUserRpcServiceClient(m.cli.Conn())
	return client.GetUserInfoById(ctx, in, opts...)
}
