// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: finance.proto

package liveexchangeraterpcservice

import (
	"context"

	"github.com/hanyougame/live-proto/proto-gen-go/finance/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAudit                      = v1.AddAudit
	AddAuditReq                   = v1.AddAuditReq
	AddAuditResp                  = v1.AddAuditResp
	AddWithdrawLimitReq           = v1.AddWithdrawLimitReq
	AddWithdrawLimitResp          = v1.AddWithdrawLimitResp
	AuditInfo                     = v1.AuditInfo
	AutoWithdrawJudgeReq          = v1.AutoWithdrawJudgeReq
	AutoWithdrawJudgeResp         = v1.AutoWithdrawJudgeResp
	AutoWithdrawMatchReq          = v1.AutoWithdrawMatchReq
	AutoWithdrawMatchResp         = v1.AutoWithdrawMatchResp
	AutoWithdrawReq               = v1.AutoWithdrawReq
	AutoWithdrawResp              = v1.AutoWithdrawResp
	BalanceReq                    = v1.BalanceReq
	BalanceResp                   = v1.BalanceResp
	BatchAddAuditReq              = v1.BatchAddAuditReq
	BatchAddAuditResp             = v1.BatchAddAuditResp
	CalcRechargeReq               = v1.CalcRechargeReq
	CalcRechargeResp              = v1.CalcRechargeResp
	CalcWithdrawFeeReq            = v1.CalcWithdrawFeeReq
	CalcWithdrawFeeResp           = v1.CalcWithdrawFeeResp
	ExchangeRateReq               = v1.ExchangeRateReq
	ExchangeRateResp              = v1.ExchangeRateResp
	GetAuditInfoReq               = v1.GetAuditInfoReq
	GetAuditInfoResp              = v1.GetAuditInfoResp
	GetAuditListReq               = v1.GetAuditListReq
	GetAuditListResp              = v1.GetAuditListResp
	PayInReq                      = v1.PayInReq
	PayInResp                     = v1.PayInResp
	PayInStatusReq                = v1.PayInStatusReq
	PayInStatusResp               = v1.PayInStatusResp
	PayOutReq                     = v1.PayOutReq
	PayOutResp                    = v1.PayOutResp
	PayOutStatusReq               = v1.PayOutStatusReq
	PayOutStatusResp              = v1.PayOutStatusResp
	ReWithdrawReq                 = v1.ReWithdrawReq
	ReWithdrawResp                = v1.ReWithdrawResp
	RechargeReq                   = v1.RechargeReq
	RechargeResp                  = v1.RechargeResp
	UpdateAuditAmountReq          = v1.UpdateAuditAmountReq
	UpdateAuditAmountResp         = v1.UpdateAuditAmountResp
	UpdateWithdrawAmountReq       = v1.UpdateWithdrawAmountReq
	UpdateWithdrawAmountResp      = v1.UpdateWithdrawAmountResp
	UpdateWithdrawLimitAmountReq  = v1.UpdateWithdrawLimitAmountReq
	UpdateWithdrawLimitAmountResp = v1.UpdateWithdrawLimitAmountResp
	WithdrawReq                   = v1.WithdrawReq
	WithdrawResp                  = v1.WithdrawResp

	LiveExchangeRateRpcService interface {
		// 获取汇率
		GetExchangeRate(ctx context.Context, in *ExchangeRateReq, opts ...grpc.CallOption) (*ExchangeRateResp, error)
	}

	defaultLiveExchangeRateRpcService struct {
		cli zrpc.Client
	}
)

func NewLiveExchangeRateRpcService(cli zrpc.Client) LiveExchangeRateRpcService {
	return &defaultLiveExchangeRateRpcService{
		cli: cli,
	}
}

// 获取汇率
func (m *defaultLiveExchangeRateRpcService) GetExchangeRate(ctx context.Context, in *ExchangeRateReq, opts ...grpc.CallOption) (*ExchangeRateResp, error) {
	client := v1.NewLiveExchangeRateRpcServiceClient(m.cli.Conn())
	return client.GetExchangeRate(ctx, in, opts...)
}
