// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: mqmsg/v1/mqmsg.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MqMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MqMsgReq) Reset() {
	*x = MqMsgReq{}
	mi := &file_mqmsg_v1_mqmsg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MqMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqMsgReq) ProtoMessage() {}

func (x *MqMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_mqmsg_v1_mqmsg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqMsgReq.ProtoReflect.Descriptor instead.
func (*MqMsgReq) Descriptor() ([]byte, []int) {
	return file_mqmsg_v1_mqmsg_proto_rawDescGZIP(), []int{0}
}

type MqMsgReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MqMsgReply) Reset() {
	*x = MqMsgReply{}
	mi := &file_mqmsg_v1_mqmsg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MqMsgReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqMsgReply) ProtoMessage() {}

func (x *MqMsgReply) ProtoReflect() protoreflect.Message {
	mi := &file_mqmsg_v1_mqmsg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqMsgReply.ProtoReflect.Descriptor instead.
func (*MqMsgReply) Descriptor() ([]byte, []int) {
	return file_mqmsg_v1_mqmsg_proto_rawDescGZIP(), []int{1}
}

type MqDepWdlTripartiteMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GamePlatformId int64  `protobuf:"varint,1,opt,name=game_platform_id,json=gamePlatformId,proto3" json:"game_platform_id,omitempty"` //游戏平台key  唯一标识
	GameId         int64  `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                           //游戏标志
	UserId         int64  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                           //用户ID
	CurrencyCode   string `protobuf:"bytes,4,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`          //货币Code
	Amount         int64  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`                                         //金额  整数且大于0
	GameOrderNo    string `protobuf:"bytes,6,opt,name=game_order_no,json=gameOrderNo,proto3" json:"game_order_no,omitempty"`           // 订单号
	TransferType   int64  `protobuf:"varint,7,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`         //交易类型 1转入,2转出
	GameName       string `protobuf:"bytes,8,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`                      //游戏名称
}

func (x *MqDepWdlTripartiteMsg) Reset() {
	*x = MqDepWdlTripartiteMsg{}
	mi := &file_mqmsg_v1_mqmsg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MqDepWdlTripartiteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqDepWdlTripartiteMsg) ProtoMessage() {}

func (x *MqDepWdlTripartiteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_mqmsg_v1_mqmsg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqDepWdlTripartiteMsg.ProtoReflect.Descriptor instead.
func (*MqDepWdlTripartiteMsg) Descriptor() ([]byte, []int) {
	return file_mqmsg_v1_mqmsg_proto_rawDescGZIP(), []int{2}
}

func (x *MqDepWdlTripartiteMsg) GetGamePlatformId() int64 {
	if x != nil {
		return x.GamePlatformId
	}
	return 0
}

func (x *MqDepWdlTripartiteMsg) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *MqDepWdlTripartiteMsg) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MqDepWdlTripartiteMsg) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *MqDepWdlTripartiteMsg) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MqDepWdlTripartiteMsg) GetGameOrderNo() string {
	if x != nil {
		return x.GameOrderNo
	}
	return ""
}

func (x *MqDepWdlTripartiteMsg) GetTransferType() int64 {
	if x != nil {
		return x.TransferType
	}
	return 0
}

func (x *MqDepWdlTripartiteMsg) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

var File_mqmsg_v1_mqmsg_proto protoreflect.FileDescriptor

var file_mqmsg_v1_mqmsg_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x71, 0x6d, 0x73, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x71, 0x6d, 0x73, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x71, 0x6d, 0x73, 0x67, 0x2e, 0x76, 0x31,
	0x22, 0x0a, 0x0a, 0x08, 0x4d, 0x71, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x22, 0x0c, 0x0a, 0x0a,
	0x4d, 0x71, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x96, 0x02, 0x0a, 0x15, 0x4d,
	0x71, 0x44, 0x65, 0x70, 0x57, 0x64, 0x6c, 0x54, 0x72, 0x69, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x65, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x10, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e,
	0x67, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a,
	0x0d, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e,
	0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mqmsg_v1_mqmsg_proto_rawDescOnce sync.Once
	file_mqmsg_v1_mqmsg_proto_rawDescData = file_mqmsg_v1_mqmsg_proto_rawDesc
)

func file_mqmsg_v1_mqmsg_proto_rawDescGZIP() []byte {
	file_mqmsg_v1_mqmsg_proto_rawDescOnce.Do(func() {
		file_mqmsg_v1_mqmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_mqmsg_v1_mqmsg_proto_rawDescData)
	})
	return file_mqmsg_v1_mqmsg_proto_rawDescData
}

var file_mqmsg_v1_mqmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mqmsg_v1_mqmsg_proto_goTypes = []any{
	(*MqMsgReq)(nil),              // 0: mqmsg.v1.MqMsgReq
	(*MqMsgReply)(nil),            // 1: mqmsg.v1.MqMsgReply
	(*MqDepWdlTripartiteMsg)(nil), // 2: mqmsg.v1.MqDepWdlTripartiteMsg
}
var file_mqmsg_v1_mqmsg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mqmsg_v1_mqmsg_proto_init() }
func file_mqmsg_v1_mqmsg_proto_init() {
	if File_mqmsg_v1_mqmsg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mqmsg_v1_mqmsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mqmsg_v1_mqmsg_proto_goTypes,
		DependencyIndexes: file_mqmsg_v1_mqmsg_proto_depIdxs,
		MessageInfos:      file_mqmsg_v1_mqmsg_proto_msgTypes,
	}.Build()
	File_mqmsg_v1_mqmsg_proto = out.File
	file_mqmsg_v1_mqmsg_proto_rawDesc = nil
	file_mqmsg_v1_mqmsg_proto_goTypes = nil
	file_mqmsg_v1_mqmsg_proto_depIdxs = nil
}
