// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: activity.proto

package liveactivityinnerservice

import (
	"context"

	"github.com/hanyougame/live-proto/proto-gen-go/activity/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActivityReply             = v1.ActivityReply
	ActivityReq               = v1.ActivityReq
	LuckySpinEventReq         = v1.LuckySpinEventReq
	RedPacketCampaignEventReq = v1.RedPacketCampaignEventReq

	LiveActivityInnerService interface {
		// 抢红包活动事件
		RedPacketCampaignEvent(ctx context.Context, in *RedPacketCampaignEventReq, opts ...grpc.CallOption) (*ActivityReply, error)
		// 幸运转盘活动事件
		LuckySpinEvent(ctx context.Context, in *LuckySpinEventReq, opts ...grpc.CallOption) (*ActivityReply, error)
	}

	defaultLiveActivityInnerService struct {
		cli zrpc.Client
	}
)

func NewLiveActivityInnerService(cli zrpc.Client) LiveActivityInnerService {
	return &defaultLiveActivityInnerService{
		cli: cli,
	}
}

// 抢红包活动事件
func (m *defaultLiveActivityInnerService) RedPacketCampaignEvent(ctx context.Context, in *RedPacketCampaignEventReq, opts ...grpc.CallOption) (*ActivityReply, error) {
	client := v1.NewLiveActivityInnerServiceClient(m.cli.Conn())
	return client.RedPacketCampaignEvent(ctx, in, opts...)
}

// 幸运转盘活动事件
func (m *defaultLiveActivityInnerService) LuckySpinEvent(ctx context.Context, in *LuckySpinEventReq, opts ...grpc.CallOption) (*ActivityReply, error) {
	client := v1.NewLiveActivityInnerServiceClient(m.cli.Conn())
	return client.LuckySpinEvent(ctx, in, opts...)
}
