// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: common/v1/enum.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode 通用错误码
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0 // 未知状态
	// 成功状态码
	ErrorCode_ERROR_CODE_SUCCESS ErrorCode = 200 // 操作成功
	// 客户端错误 4xx
	ErrorCode_ERROR_CODE_BAD_REQUEST          ErrorCode = 400 // 请求参数错误
	ErrorCode_ERROR_CODE_UNAUTHORIZED         ErrorCode = 401 // 未授权
	ErrorCode_ERROR_CODE_FORBIDDEN            ErrorCode = 403 // 禁止访问
	ErrorCode_ERROR_CODE_NOT_FOUND            ErrorCode = 404 // 资源未找到
	ErrorCode_ERROR_CODE_METHOD_NOT_ALLOWED   ErrorCode = 405 // 方法不允许
	ErrorCode_ERROR_CODE_CONFLICT             ErrorCode = 409 // 资源冲突
	ErrorCode_ERROR_CODE_UNPROCESSABLE_ENTITY ErrorCode = 422 // 请求格式正确但语义错误
	ErrorCode_ERROR_CODE_TOO_MANY_REQUESTS    ErrorCode = 429 // 请求过于频繁
	// 服务端错误 5xx
	ErrorCode_ERROR_CODE_INTERNAL_SERVER_ERROR ErrorCode = 500 // 服务器内部错误
	ErrorCode_ERROR_CODE_NOT_IMPLEMENTED       ErrorCode = 501 // 功能未实现
	ErrorCode_ERROR_CODE_BAD_GATEWAY           ErrorCode = 502 // 网关错误或第三方服务异常
	ErrorCode_ERROR_CODE_SERVICE_UNAVAILABLE   ErrorCode = 503 // 服务不可用
	ErrorCode_ERROR_CODE_GATEWAY_TIMEOUT       ErrorCode = 504 // 网关超时
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "ERROR_CODE_UNSPECIFIED",
		200: "ERROR_CODE_SUCCESS",
		400: "ERROR_CODE_BAD_REQUEST",
		401: "ERROR_CODE_UNAUTHORIZED",
		403: "ERROR_CODE_FORBIDDEN",
		404: "ERROR_CODE_NOT_FOUND",
		405: "ERROR_CODE_METHOD_NOT_ALLOWED",
		409: "ERROR_CODE_CONFLICT",
		422: "ERROR_CODE_UNPROCESSABLE_ENTITY",
		429: "ERROR_CODE_TOO_MANY_REQUESTS",
		500: "ERROR_CODE_INTERNAL_SERVER_ERROR",
		501: "ERROR_CODE_NOT_IMPLEMENTED",
		502: "ERROR_CODE_BAD_GATEWAY",
		503: "ERROR_CODE_SERVICE_UNAVAILABLE",
		504: "ERROR_CODE_GATEWAY_TIMEOUT",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":           0,
		"ERROR_CODE_SUCCESS":               200,
		"ERROR_CODE_BAD_REQUEST":           400,
		"ERROR_CODE_UNAUTHORIZED":          401,
		"ERROR_CODE_FORBIDDEN":             403,
		"ERROR_CODE_NOT_FOUND":             404,
		"ERROR_CODE_METHOD_NOT_ALLOWED":    405,
		"ERROR_CODE_CONFLICT":              409,
		"ERROR_CODE_UNPROCESSABLE_ENTITY":  422,
		"ERROR_CODE_TOO_MANY_REQUESTS":     429,
		"ERROR_CODE_INTERNAL_SERVER_ERROR": 500,
		"ERROR_CODE_NOT_IMPLEMENTED":       501,
		"ERROR_CODE_BAD_GATEWAY":           502,
		"ERROR_CODE_SERVICE_UNAVAILABLE":   503,
		"ERROR_CODE_GATEWAY_TIMEOUT":       504,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_enum_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_v1_enum_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_enum_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_enum_proto protoreflect.FileDescriptor

const file_common_v1_enum_proto_rawDesc = "" +
	"\n" +
	"\x14common/v1/enum.proto\x12\tcommon.v1*\xe3\x03\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x12ERROR_CODE_SUCCESS\x10\xc8\x01\x12\x1b\n" +
	"\x16ERROR_CODE_BAD_REQUEST\x10\x90\x03\x12\x1c\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x91\x03\x12\x19\n" +
	"\x14ERROR_CODE_FORBIDDEN\x10\x93\x03\x12\x19\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x94\x03\x12\"\n" +
	"\x1dERROR_CODE_METHOD_NOT_ALLOWED\x10\x95\x03\x12\x18\n" +
	"\x13ERROR_CODE_CONFLICT\x10\x99\x03\x12$\n" +
	"\x1fERROR_CODE_UNPROCESSABLE_ENTITY\x10\xa6\x03\x12!\n" +
	"\x1cERROR_CODE_TOO_MANY_REQUESTS\x10\xad\x03\x12%\n" +
	" ERROR_CODE_INTERNAL_SERVER_ERROR\x10\xf4\x03\x12\x1f\n" +
	"\x1aERROR_CODE_NOT_IMPLEMENTED\x10\xf5\x03\x12\x1b\n" +
	"\x16ERROR_CODE_BAD_GATEWAY\x10\xf6\x03\x12#\n" +
	"\x1eERROR_CODE_SERVICE_UNAVAILABLE\x10\xf7\x03\x12\x1f\n" +
	"\x1aERROR_CODE_GATEWAY_TIMEOUT\x10\xf8\x03B9Z7github.com/hanyougame/live-proto/proto-gen-go/common/v1b\x06proto3"

var (
	file_common_v1_enum_proto_rawDescOnce sync.Once
	file_common_v1_enum_proto_rawDescData []byte
)

func file_common_v1_enum_proto_rawDescGZIP() []byte {
	file_common_v1_enum_proto_rawDescOnce.Do(func() {
		file_common_v1_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_enum_proto_rawDesc), len(file_common_v1_enum_proto_rawDesc)))
	})
	return file_common_v1_enum_proto_rawDescData
}

var file_common_v1_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_enum_proto_goTypes = []any{
	(ErrorCode)(0), // 0: common.v1.ErrorCode
}
var file_common_v1_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_enum_proto_init() }
func file_common_v1_enum_proto_init() {
	if File_common_v1_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_enum_proto_rawDesc), len(file_common_v1_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_enum_proto_goTypes,
		DependencyIndexes: file_common_v1_enum_proto_depIdxs,
		EnumInfos:         file_common_v1_enum_proto_enumTypes,
	}.Build()
	File_common_v1_enum_proto = out.File
	file_common_v1_enum_proto_goTypes = nil
	file_common_v1_enum_proto_depIdxs = nil
}
