// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: proto/activity/v1/activity.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_UNKNOWN  EventType = 0
	EventType_BET      EventType = 1 // 打码
	EventType_RECHARGE EventType = 2 // 充值
	EventType_REGISTER EventType = 3 // 注册
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "UNKNOWN",
		1: "BET",
		2: "RECHARGE",
		3: "REGISTER",
	}
	EventType_value = map[string]int32{
		"UNKNOWN":  0,
		"BET":      1,
		"RECHARGE": 2,
		"REGISTER": 3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_activity_v1_activity_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_proto_activity_v1_activity_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{0}
}

// 新增 SpinType 枚举
type SpinType int32

const (
	SpinType_SPIN_TYPE_UNKNOWN SpinType = 0
	SpinType_SPIN_TYPE_SILVER  SpinType = 1 // 白银转盘
	SpinType_SPIN_TYPE_GOLD    SpinType = 2 // 黄金转盘
	SpinType_SPIN_TYPE_DIAMOND SpinType = 3 // 钻石转盘
)

// Enum value maps for SpinType.
var (
	SpinType_name = map[int32]string{
		0: "SPIN_TYPE_UNKNOWN",
		1: "SPIN_TYPE_SILVER",
		2: "SPIN_TYPE_GOLD",
		3: "SPIN_TYPE_DIAMOND",
	}
	SpinType_value = map[string]int32{
		"SPIN_TYPE_UNKNOWN": 0,
		"SPIN_TYPE_SILVER":  1,
		"SPIN_TYPE_GOLD":    2,
		"SPIN_TYPE_DIAMOND": 3,
	}
)

func (x SpinType) Enum() *SpinType {
	p := new(SpinType)
	*p = x
	return p
}

func (x SpinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpinType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_activity_v1_activity_proto_enumTypes[1].Descriptor()
}

func (SpinType) Type() protoreflect.EnumType {
	return &file_proto_activity_v1_activity_proto_enumTypes[1]
}

func (x SpinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpinType.Descriptor instead.
func (SpinType) EnumDescriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{1}
}

type ActivityReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityReq) Reset() {
	*x = ActivityReq{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityReq) ProtoMessage() {}

func (x *ActivityReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityReq.ProtoReflect.Descriptor instead.
func (*ActivityReq) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{0}
}

type ActivityReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityReply) Reset() {
	*x = ActivityReply{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityReply) ProtoMessage() {}

func (x *ActivityReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityReply.ProtoReflect.Descriptor instead.
func (*ActivityReply) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{1}
}

type GetUserInviteCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户id
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` // 活动id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInviteCountReq) Reset() {
	*x = GetUserInviteCountReq{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInviteCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInviteCountReq) ProtoMessage() {}

func (x *GetUserInviteCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInviteCountReq.ProtoReflect.Descriptor instead.
func (*GetUserInviteCountReq) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInviteCountReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserInviteCountReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type GetUserInviteCountReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCount   int32                  `protobuf:"varint,1,opt,name=invite_count,json=inviteCount,proto3" json:"invite_count,omitempty"` // 有效邀请人数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInviteCountReply) Reset() {
	*x = GetUserInviteCountReply{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInviteCountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInviteCountReply) ProtoMessage() {}

func (x *GetUserInviteCountReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInviteCountReply.ProtoReflect.Descriptor instead.
func (*GetUserInviteCountReply) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInviteCountReply) GetInviteCount() int32 {
	if x != nil {
		return x.InviteCount
	}
	return 0
}

type RewardListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*RewardData          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // 奖励数据列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardListReply) Reset() {
	*x = RewardListReply{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardListReply) ProtoMessage() {}

func (x *RewardListReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardListReply.ProtoReflect.Descriptor instead.
func (*RewardListReply) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{4}
}

func (x *RewardListReply) GetData() []*RewardData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RewardData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                  // 用户id
	Reward        int64                  `protobuf:"varint,2,opt,name=reward,proto3" json:"reward,omitempty"`                                               // 奖励金额
	RewardTime    int32                  `protobuf:"varint,3,opt,name=reward_time,json=rewardTime,proto3" json:"reward_time,omitempty"`                     // 奖励时间
	SpinType      SpinType               `protobuf:"varint,4,opt,name=spin_type,json=spinType,proto3,enum=activity.v1.SpinType" json:"spin_type,omitempty"` // 转盘类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardData) Reset() {
	*x = RewardData{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardData) ProtoMessage() {}

func (x *RewardData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardData.ProtoReflect.Descriptor instead.
func (*RewardData) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{5}
}

func (x *RewardData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RewardData) GetReward() int64 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *RewardData) GetRewardTime() int32 {
	if x != nil {
		return x.RewardTime
	}
	return 0
}

func (x *RewardData) GetSpinType() SpinType {
	if x != nil {
		return x.SpinType
	}
	return SpinType_SPIN_TYPE_UNKNOWN
}

type GetLuckyPointListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 用户id
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` // 活动id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLuckyPointListReq) Reset() {
	*x = GetLuckyPointListReq{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLuckyPointListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLuckyPointListReq) ProtoMessage() {}

func (x *GetLuckyPointListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLuckyPointListReq.ProtoReflect.Descriptor instead.
func (*GetLuckyPointListReq) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{6}
}

func (x *GetLuckyPointListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLuckyPointListReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type RewardListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int64                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` // 活动id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardListReq) Reset() {
	*x = RewardListReq{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardListReq) ProtoMessage() {}

func (x *RewardListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardListReq.ProtoReflect.Descriptor instead.
func (*RewardListReq) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{7}
}

func (x *RewardListReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type LuckyPointsUsedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpinType      SpinType               `protobuf:"varint,1,opt,name=spin_type,json=spinType,proto3,enum=activity.v1.SpinType" json:"spin_type,omitempty"`                            // 转盘类型
	UsedList      []*UseLuckyPoint       `protobuf:"bytes,2,rep,name=UsedList,proto3" json:"UsedList,omitempty"`                                                                       // 使用的幸运值列表
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                            // 用户id
	CreateAt      int32                  `protobuf:"varint,4,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`                                                      // 创建时间
	Detail        map[string]string      `protobuf:"bytes,5,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外信息
	UserName      string                 `protobuf:"bytes,6,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                                                       // 用户名
	PointBefore   int64                  `protobuf:"varint,7,opt,name=point_before,json=pointBefore,proto3" json:"point_before,omitempty"`                                             // 领取前的幸运值
	PointAfter    int64                  `protobuf:"varint,8,opt,name=point_after,json=pointAfter,proto3" json:"point_after,omitempty"`                                                // 领取后的幸运值
	Point         int32                  `protobuf:"varint,9,opt,name=point,proto3" json:"point,omitempty"`                                                                            // 幸运值
	Reward        int32                  `protobuf:"varint,10,opt,name=reward,proto3" json:"reward,omitempty"`                                                                         // 奖励金额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuckyPointsUsedItem) Reset() {
	*x = LuckyPointsUsedItem{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuckyPointsUsedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuckyPointsUsedItem) ProtoMessage() {}

func (x *LuckyPointsUsedItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuckyPointsUsedItem.ProtoReflect.Descriptor instead.
func (*LuckyPointsUsedItem) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{8}
}

func (x *LuckyPointsUsedItem) GetSpinType() SpinType {
	if x != nil {
		return x.SpinType
	}
	return SpinType_SPIN_TYPE_UNKNOWN
}

func (x *LuckyPointsUsedItem) GetUsedList() []*UseLuckyPoint {
	if x != nil {
		return x.UsedList
	}
	return nil
}

func (x *LuckyPointsUsedItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LuckyPointsUsedItem) GetCreateAt() int32 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *LuckyPointsUsedItem) GetDetail() map[string]string {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *LuckyPointsUsedItem) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LuckyPointsUsedItem) GetPointBefore() int64 {
	if x != nil {
		return x.PointBefore
	}
	return 0
}

func (x *LuckyPointsUsedItem) GetPointAfter() int64 {
	if x != nil {
		return x.PointAfter
	}
	return 0
}

func (x *LuckyPointsUsedItem) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *LuckyPointsUsedItem) GetReward() int32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

type LuckyPointsUsedListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*LuckyPointsUsedItem `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuckyPointsUsedListReply) Reset() {
	*x = LuckyPointsUsedListReply{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuckyPointsUsedListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuckyPointsUsedListReply) ProtoMessage() {}

func (x *LuckyPointsUsedListReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuckyPointsUsedListReply.ProtoReflect.Descriptor instead.
func (*LuckyPointsUsedListReply) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{9}
}

func (x *LuckyPointsUsedListReply) GetData() []*LuckyPointsUsedItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type LuckyPointsAddItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                            // 用户id
	Point         int32                  `protobuf:"varint,2,opt,name=point,proto3" json:"point,omitempty"`                                                                            // 幸运值
	CreateAt      int32                  `protobuf:"varint,3,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`                                                      // 创建时间
	ClaimId       int32                  `protobuf:"varint,4,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`                                                         // 领取id
	Detail        map[string]string      `protobuf:"bytes,5,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外信息
	UserName      string                 `protobuf:"bytes,6,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                                                       // 用户名
	PointBefore   int64                  `protobuf:"varint,7,opt,name=point_before,json=pointBefore,proto3" json:"point_before,omitempty"`                                             // 领取前的幸运值
	PointAfter    int64                  `protobuf:"varint,8,opt,name=point_after,json=pointAfter,proto3" json:"point_after,omitempty"`                                                // 领取后的幸运值
	Condition     string                 `protobuf:"bytes,9,opt,name=condition,proto3" json:"condition,omitempty"`                                                                     // 条件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuckyPointsAddItem) Reset() {
	*x = LuckyPointsAddItem{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuckyPointsAddItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuckyPointsAddItem) ProtoMessage() {}

func (x *LuckyPointsAddItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuckyPointsAddItem.ProtoReflect.Descriptor instead.
func (*LuckyPointsAddItem) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{10}
}

func (x *LuckyPointsAddItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LuckyPointsAddItem) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *LuckyPointsAddItem) GetCreateAt() int32 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *LuckyPointsAddItem) GetClaimId() int32 {
	if x != nil {
		return x.ClaimId
	}
	return 0
}

func (x *LuckyPointsAddItem) GetDetail() map[string]string {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *LuckyPointsAddItem) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LuckyPointsAddItem) GetPointBefore() int64 {
	if x != nil {
		return x.PointBefore
	}
	return 0
}

func (x *LuckyPointsAddItem) GetPointAfter() int64 {
	if x != nil {
		return x.PointAfter
	}
	return 0
}

func (x *LuckyPointsAddItem) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

type LuckyPointsAddListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*LuckyPointsAddItem  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuckyPointsAddListReply) Reset() {
	*x = LuckyPointsAddListReply{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuckyPointsAddListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuckyPointsAddListReply) ProtoMessage() {}

func (x *LuckyPointsAddListReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuckyPointsAddListReply.ProtoReflect.Descriptor instead.
func (*LuckyPointsAddListReply) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{11}
}

func (x *LuckyPointsAddListReply) GetData() []*LuckyPointsAddItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type UseLuckyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       int32                  `protobuf:"varint,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"` // 领取id
	Point         int32                  `protobuf:"varint,2,opt,name=point,proto3" json:"point,omitempty"`                    // 幸运值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseLuckyPoint) Reset() {
	*x = UseLuckyPoint{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseLuckyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseLuckyPoint) ProtoMessage() {}

func (x *UseLuckyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseLuckyPoint.ProtoReflect.Descriptor instead.
func (*UseLuckyPoint) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{12}
}

func (x *UseLuckyPoint) GetClaimId() int32 {
	if x != nil {
		return x.ClaimId
	}
	return 0
}

func (x *UseLuckyPoint) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

type UseLuckyPointReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                            // 用户id
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`                                                // 活动id
	Reward        int32                  `protobuf:"varint,3,opt,name=reward,proto3" json:"reward,omitempty"`                                                                          // 奖励金额
	Point         int32                  `protobuf:"varint,4,opt,name=point,proto3" json:"point,omitempty"`                                                                            // 消耗的总幸运值
	SpinType      SpinType               `protobuf:"varint,5,opt,name=spin_type,json=spinType,proto3,enum=activity.v1.SpinType" json:"spin_type,omitempty"`                            // 转盘类型
	Detail        map[string]string      `protobuf:"bytes,6,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外信息
	CycleId       int32                  `protobuf:"varint,7,opt,name=cycle_id,json=cycleId,proto3" json:"cycle_id,omitempty"`                                                         // 周期id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseLuckyPointReq) Reset() {
	*x = UseLuckyPointReq{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseLuckyPointReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseLuckyPointReq) ProtoMessage() {}

func (x *UseLuckyPointReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseLuckyPointReq.ProtoReflect.Descriptor instead.
func (*UseLuckyPointReq) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{13}
}

func (x *UseLuckyPointReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UseLuckyPointReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *UseLuckyPointReq) GetReward() int32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *UseLuckyPointReq) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *UseLuckyPointReq) GetSpinType() SpinType {
	if x != nil {
		return x.SpinType
	}
	return SpinType_SPIN_TYPE_UNKNOWN
}

func (x *UseLuckyPointReq) GetDetail() map[string]string {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *UseLuckyPointReq) GetCycleId() int32 {
	if x != nil {
		return x.CycleId
	}
	return 0
}

type GetLuckyPointReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []int64                `protobuf:"varint,1,rep,packed,name=user_id,json=userId,proto3" json:"user_id,omitempty"`      // 用户id
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` // 活动id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLuckyPointReq) Reset() {
	*x = GetLuckyPointReq{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLuckyPointReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLuckyPointReq) ProtoMessage() {}

func (x *GetLuckyPointReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLuckyPointReq.ProtoReflect.Descriptor instead.
func (*GetLuckyPointReq) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{14}
}

func (x *GetLuckyPointReq) GetUserId() []int64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *GetLuckyPointReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type GetLuckyPointItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalCount     int64                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`             // 总幸运值
	ExpiredCount   int64                  `protobuf:"varint,2,opt,name=expired_count,json=expiredCount,proto3" json:"expired_count,omitempty"`       // 过期幸运值
	AvailableCount int64                  `protobuf:"varint,3,opt,name=available_count,json=availableCount,proto3" json:"available_count,omitempty"` // 可用幸运值
	UsedCount      int64                  `protobuf:"varint,4,opt,name=used_count,json=usedCount,proto3" json:"used_count,omitempty"`                // 已使用幸运值
	UserId         int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // 用户id
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLuckyPointItem) Reset() {
	*x = GetLuckyPointItem{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLuckyPointItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLuckyPointItem) ProtoMessage() {}

func (x *GetLuckyPointItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLuckyPointItem.ProtoReflect.Descriptor instead.
func (*GetLuckyPointItem) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{15}
}

func (x *GetLuckyPointItem) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetLuckyPointItem) GetExpiredCount() int64 {
	if x != nil {
		return x.ExpiredCount
	}
	return 0
}

func (x *GetLuckyPointItem) GetAvailableCount() int64 {
	if x != nil {
		return x.AvailableCount
	}
	return 0
}

func (x *GetLuckyPointItem) GetUsedCount() int64 {
	if x != nil {
		return x.UsedCount
	}
	return 0
}

func (x *GetLuckyPointItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetLuckyPointReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*GetLuckyPointItem   `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // 用户幸运值列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLuckyPointReply) Reset() {
	*x = GetLuckyPointReply{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLuckyPointReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLuckyPointReply) ProtoMessage() {}

func (x *GetLuckyPointReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLuckyPointReply.ProtoReflect.Descriptor instead.
func (*GetLuckyPointReply) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{16}
}

func (x *GetLuckyPointReply) GetData() []*GetLuckyPointItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddLuckyValReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                            // 用户id
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`                                                // 活动id
	ExpireTime    int32                  `protobuf:"varint,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`                                                // // 过期时间
	Point         int32                  `protobuf:"varint,4,opt,name=point,proto3" json:"point,omitempty"`                                                                            // 幸运值
	Condition     string                 `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`                                                                     // 条件
	EventType     string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                                                    // 事件类型
	EventData     string                 `protobuf:"bytes,7,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`                                                    // 事件数据
	Detail        map[string]string      `protobuf:"bytes,8,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLuckyValReq) Reset() {
	*x = AddLuckyValReq{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLuckyValReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLuckyValReq) ProtoMessage() {}

func (x *AddLuckyValReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLuckyValReq.ProtoReflect.Descriptor instead.
func (*AddLuckyValReq) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{17}
}

func (x *AddLuckyValReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddLuckyValReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *AddLuckyValReq) GetExpireTime() int32 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *AddLuckyValReq) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *AddLuckyValReq) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *AddLuckyValReq) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AddLuckyValReq) GetEventData() string {
	if x != nil {
		return x.EventData
	}
	return ""
}

func (x *AddLuckyValReq) GetDetail() map[string]string {
	if x != nil {
		return x.Detail
	}
	return nil
}

type RedPacketCampaignEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedPacketCampaignEventReq) Reset() {
	*x = RedPacketCampaignEventReq{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedPacketCampaignEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedPacketCampaignEventReq) ProtoMessage() {}

func (x *RedPacketCampaignEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedPacketCampaignEventReq.ProtoReflect.Descriptor instead.
func (*RedPacketCampaignEventReq) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{18}
}

func (x *RedPacketCampaignEventReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LuckySpinEventReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=activity.v1.EventType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // 数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuckySpinEventReq) Reset() {
	*x = LuckySpinEventReq{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuckySpinEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuckySpinEventReq) ProtoMessage() {}

func (x *LuckySpinEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuckySpinEventReq.ProtoReflect.Descriptor instead.
func (*LuckySpinEventReq) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{19}
}

func (x *LuckySpinEventReq) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_UNKNOWN
}

func (x *LuckySpinEventReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CheckUserRedPacketConditionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`      // 用户id
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`    // 活动id
	PeriodIndex   int64                  `protobuf:"varint,3,opt,name=period_index,json=periodIndex,proto3" json:"period_index,omitempty"` // 活动阶段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserRedPacketConditionReq) Reset() {
	*x = CheckUserRedPacketConditionReq{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserRedPacketConditionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserRedPacketConditionReq) ProtoMessage() {}

func (x *CheckUserRedPacketConditionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserRedPacketConditionReq.ProtoReflect.Descriptor instead.
func (*CheckUserRedPacketConditionReq) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{20}
}

func (x *CheckUserRedPacketConditionReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *CheckUserRedPacketConditionReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *CheckUserRedPacketConditionReq) GetPeriodIndex() int64 {
	if x != nil {
		return x.PeriodIndex
	}
	return 0
}

type CheckUserRedPacketConditionReply struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserPacketConditions map[int64]bool         `protobuf:"bytes,1,rep,name=user_packet_conditions,json=userPacketConditions,proto3" json:"user_packet_conditions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CheckUserRedPacketConditionReply) Reset() {
	*x = CheckUserRedPacketConditionReply{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserRedPacketConditionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserRedPacketConditionReply) ProtoMessage() {}

func (x *CheckUserRedPacketConditionReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserRedPacketConditionReply.ProtoReflect.Descriptor instead.
func (*CheckUserRedPacketConditionReply) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{21}
}

func (x *CheckUserRedPacketConditionReply) GetUserPacketConditions() map[int64]bool {
	if x != nil {
		return x.UserPacketConditions
	}
	return nil
}

type IncreaseUserRedPacketCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	PeriodIndex   int64                  `protobuf:"varint,3,opt,name=period_index,json=periodIndex,proto3" json:"period_index,omitempty"`
	CurrentDate   string                 `protobuf:"bytes,4,opt,name=current_date,json=currentDate,proto3" json:"current_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncreaseUserRedPacketCountReq) Reset() {
	*x = IncreaseUserRedPacketCountReq{}
	mi := &file_proto_activity_v1_activity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncreaseUserRedPacketCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncreaseUserRedPacketCountReq) ProtoMessage() {}

func (x *IncreaseUserRedPacketCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_activity_v1_activity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncreaseUserRedPacketCountReq.ProtoReflect.Descriptor instead.
func (*IncreaseUserRedPacketCountReq) Descriptor() ([]byte, []int) {
	return file_proto_activity_v1_activity_proto_rawDescGZIP(), []int{22}
}

func (x *IncreaseUserRedPacketCountReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IncreaseUserRedPacketCountReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *IncreaseUserRedPacketCountReq) GetPeriodIndex() int64 {
	if x != nil {
		return x.PeriodIndex
	}
	return 0
}

func (x *IncreaseUserRedPacketCountReq) GetCurrentDate() string {
	if x != nil {
		return x.CurrentDate
	}
	return ""
}

var File_proto_activity_v1_activity_proto protoreflect.FileDescriptor

const file_proto_activity_v1_activity_proto_rawDesc = "" +
	"\n" +
	" proto/activity/v1/activity.proto\x12\vactivity.v1\"\r\n" +
	"\vActivityReq\"\x0f\n" +
	"\rActivityReply\"Q\n" +
	"\x15GetUserInviteCountReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\"<\n" +
	"\x17GetUserInviteCountReply\x12!\n" +
	"\finvite_count\x18\x01 \x01(\x05R\vinviteCount\">\n" +
	"\x0fRewardListReply\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.activity.v1.RewardDataR\x04data\"\x92\x01\n" +
	"\n" +
	"RewardData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reward\x18\x02 \x01(\x03R\x06reward\x12\x1f\n" +
	"\vreward_time\x18\x03 \x01(\x05R\n" +
	"rewardTime\x122\n" +
	"\tspin_type\x18\x04 \x01(\x0e2\x15.activity.v1.SpinTypeR\bspinType\"P\n" +
	"\x14GetLuckyPointListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\"0\n" +
	"\rRewardListReq\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x03R\n" +
	"activityId\"\xc7\x03\n" +
	"\x13LuckyPointsUsedItem\x122\n" +
	"\tspin_type\x18\x01 \x01(\x0e2\x15.activity.v1.SpinTypeR\bspinType\x126\n" +
	"\bUsedList\x18\x02 \x03(\v2\x1a.activity.v1.UseLuckyPointR\bUsedList\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tcreate_at\x18\x04 \x01(\x05R\bcreateAt\x12D\n" +
	"\x06detail\x18\x05 \x03(\v2,.activity.v1.LuckyPointsUsedItem.DetailEntryR\x06detail\x12\x1b\n" +
	"\tuser_name\x18\x06 \x01(\tR\buserName\x12!\n" +
	"\fpoint_before\x18\a \x01(\x03R\vpointBefore\x12\x1f\n" +
	"\vpoint_after\x18\b \x01(\x03R\n" +
	"pointAfter\x12\x14\n" +
	"\x05point\x18\t \x01(\x05R\x05point\x12\x16\n" +
	"\x06reward\x18\n" +
	" \x01(\x05R\x06reward\x1a9\n" +
	"\vDetailEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x18LuckyPointsUsedListReply\x124\n" +
	"\x04data\x18\x01 \x03(\v2 .activity.v1.LuckyPointsUsedItemR\x04data\"\xfa\x02\n" +
	"\x12LuckyPointsAddItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05point\x18\x02 \x01(\x05R\x05point\x12\x1b\n" +
	"\tcreate_at\x18\x03 \x01(\x05R\bcreateAt\x12\x19\n" +
	"\bclaim_id\x18\x04 \x01(\x05R\aclaimId\x12C\n" +
	"\x06detail\x18\x05 \x03(\v2+.activity.v1.LuckyPointsAddItem.DetailEntryR\x06detail\x12\x1b\n" +
	"\tuser_name\x18\x06 \x01(\tR\buserName\x12!\n" +
	"\fpoint_before\x18\a \x01(\x03R\vpointBefore\x12\x1f\n" +
	"\vpoint_after\x18\b \x01(\x03R\n" +
	"pointAfter\x12\x1c\n" +
	"\tcondition\x18\t \x01(\tR\tcondition\x1a9\n" +
	"\vDetailEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x17LuckyPointsAddListReply\x123\n" +
	"\x04data\x18\x01 \x03(\v2\x1f.activity.v1.LuckyPointsAddItemR\x04data\"@\n" +
	"\rUseLuckyPoint\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\x05R\aclaimId\x12\x14\n" +
	"\x05point\x18\x02 \x01(\x05R\x05point\"\xc7\x02\n" +
	"\x10UseLuckyPointReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12\x16\n" +
	"\x06reward\x18\x03 \x01(\x05R\x06reward\x12\x14\n" +
	"\x05point\x18\x04 \x01(\x05R\x05point\x122\n" +
	"\tspin_type\x18\x05 \x01(\x0e2\x15.activity.v1.SpinTypeR\bspinType\x12A\n" +
	"\x06detail\x18\x06 \x03(\v2).activity.v1.UseLuckyPointReq.DetailEntryR\x06detail\x12\x19\n" +
	"\bcycle_id\x18\a \x01(\x05R\acycleId\x1a9\n" +
	"\vDetailEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x10GetLuckyPointReq\x12\x17\n" +
	"\auser_id\x18\x01 \x03(\x03R\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\"\xba\x01\n" +
	"\x11GetLuckyPointItem\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x12#\n" +
	"\rexpired_count\x18\x02 \x01(\x03R\fexpiredCount\x12'\n" +
	"\x0favailable_count\x18\x03 \x01(\x03R\x0eavailableCount\x12\x1d\n" +
	"\n" +
	"used_count\x18\x04 \x01(\x03R\tusedCount\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\"H\n" +
	"\x12GetLuckyPointReply\x122\n" +
	"\x04data\x18\x01 \x03(\v2\x1e.activity.v1.GetLuckyPointItemR\x04data\"\xd9\x02\n" +
	"\x0eAddLuckyValReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12\x1f\n" +
	"\vexpire_time\x18\x03 \x01(\x05R\n" +
	"expireTime\x12\x14\n" +
	"\x05point\x18\x04 \x01(\x05R\x05point\x12\x1c\n" +
	"\tcondition\x18\x05 \x01(\tR\tcondition\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"event_data\x18\a \x01(\tR\teventData\x12?\n" +
	"\x06detail\x18\b \x03(\v2'.activity.v1.AddLuckyValReq.DetailEntryR\x06detail\x1a9\n" +
	"\vDetailEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x19RedPacketCampaignEventReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"S\n" +
	"\x11LuckySpinEventReq\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.activity.v1.EventTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x7f\n" +
	"\x1eCheckUserRedPacketConditionReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12!\n" +
	"\fperiod_index\x18\x03 \x01(\x03R\vperiodIndex\"\xea\x01\n" +
	" CheckUserRedPacketConditionReply\x12}\n" +
	"\x16user_packet_conditions\x18\x01 \x03(\v2G.activity.v1.CheckUserRedPacketConditionReply.UserPacketConditionsEntryR\x14userPacketConditions\x1aG\n" +
	"\x19UserPacketConditionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x1dIncreaseUserRedPacketCountReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12!\n" +
	"\fperiod_index\x18\x03 \x01(\x03R\vperiodIndex\x12!\n" +
	"\fcurrent_date\x18\x04 \x01(\tR\vcurrentDate*=\n" +
	"\tEventType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03BET\x10\x01\x12\f\n" +
	"\bRECHARGE\x10\x02\x12\f\n" +
	"\bREGISTER\x10\x03*b\n" +
	"\bSpinType\x12\x15\n" +
	"\x11SPIN_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10SPIN_TYPE_SILVER\x10\x01\x12\x12\n" +
	"\x0eSPIN_TYPE_GOLD\x10\x02\x12\x15\n" +
	"\x11SPIN_TYPE_DIAMOND\x10\x032\xfa\a\n" +
	"\x18LiveActivityInnerService\x12\\\n" +
	"\x16RedPacketCampaignEvent\x12&.activity.v1.RedPacketCampaignEventReq\x1a\x1a.activity.v1.ActivityReply\x12y\n" +
	"\x1bCheckUserRedPacketCondition\x12+.activity.v1.CheckUserRedPacketConditionReq\x1a-.activity.v1.CheckUserRedPacketConditionReply\x12d\n" +
	"\x1aIncreaseUserRedPacketCount\x12*.activity.v1.IncreaseUserRedPacketCountReq\x1a\x1a.activity.v1.ActivityReply\x12L\n" +
	"\x0eLuckySpinEvent\x12\x1e.activity.v1.LuckySpinEventReq\x1a\x1a.activity.v1.ActivityReply\x12H\n" +
	"\rAddLuckyPoint\x12\x1b.activity.v1.AddLuckyValReq\x1a\x1a.activity.v1.ActivityReply\x12J\n" +
	"\rUseLuckyPoint\x12\x1d.activity.v1.UseLuckyPointReq\x1a\x1a.activity.v1.ActivityReply\x12S\n" +
	"\x11GetUserLuckyPoint\x12\x1d.activity.v1.GetLuckyPointReq\x1a\x1f.activity.v1.GetLuckyPointReply\x12]\n" +
	"\x12LuckyPointsAddList\x12!.activity.v1.GetLuckyPointListReq\x1a$.activity.v1.LuckyPointsAddListReply\x12_\n" +
	"\x13LuckyPointsUsedList\x12!.activity.v1.GetLuckyPointListReq\x1a%.activity.v1.LuckyPointsUsedListReply\x12F\n" +
	"\n" +
	"RewardList\x12\x1a.activity.v1.RewardListReq\x1a\x1c.activity.v1.RewardListReply\x12^\n" +
	"\x12GetUserInviteCount\x12\".activity.v1.GetUserInviteCountReq\x1a$.activity.v1.GetUserInviteCountReplyB\tZ\a./pb/v1b\x06proto3"

var (
	file_proto_activity_v1_activity_proto_rawDescOnce sync.Once
	file_proto_activity_v1_activity_proto_rawDescData []byte
)

func file_proto_activity_v1_activity_proto_rawDescGZIP() []byte {
	file_proto_activity_v1_activity_proto_rawDescOnce.Do(func() {
		file_proto_activity_v1_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_activity_v1_activity_proto_rawDesc), len(file_proto_activity_v1_activity_proto_rawDesc)))
	})
	return file_proto_activity_v1_activity_proto_rawDescData
}

var file_proto_activity_v1_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_activity_v1_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_activity_v1_activity_proto_goTypes = []any{
	(EventType)(0),                           // 0: activity.v1.EventType
	(SpinType)(0),                            // 1: activity.v1.SpinType
	(*ActivityReq)(nil),                      // 2: activity.v1.ActivityReq
	(*ActivityReply)(nil),                    // 3: activity.v1.ActivityReply
	(*GetUserInviteCountReq)(nil),            // 4: activity.v1.GetUserInviteCountReq
	(*GetUserInviteCountReply)(nil),          // 5: activity.v1.GetUserInviteCountReply
	(*RewardListReply)(nil),                  // 6: activity.v1.RewardListReply
	(*RewardData)(nil),                       // 7: activity.v1.RewardData
	(*GetLuckyPointListReq)(nil),             // 8: activity.v1.GetLuckyPointListReq
	(*RewardListReq)(nil),                    // 9: activity.v1.RewardListReq
	(*LuckyPointsUsedItem)(nil),              // 10: activity.v1.LuckyPointsUsedItem
	(*LuckyPointsUsedListReply)(nil),         // 11: activity.v1.LuckyPointsUsedListReply
	(*LuckyPointsAddItem)(nil),               // 12: activity.v1.LuckyPointsAddItem
	(*LuckyPointsAddListReply)(nil),          // 13: activity.v1.LuckyPointsAddListReply
	(*UseLuckyPoint)(nil),                    // 14: activity.v1.UseLuckyPoint
	(*UseLuckyPointReq)(nil),                 // 15: activity.v1.UseLuckyPointReq
	(*GetLuckyPointReq)(nil),                 // 16: activity.v1.GetLuckyPointReq
	(*GetLuckyPointItem)(nil),                // 17: activity.v1.GetLuckyPointItem
	(*GetLuckyPointReply)(nil),               // 18: activity.v1.GetLuckyPointReply
	(*AddLuckyValReq)(nil),                   // 19: activity.v1.AddLuckyValReq
	(*RedPacketCampaignEventReq)(nil),        // 20: activity.v1.RedPacketCampaignEventReq
	(*LuckySpinEventReq)(nil),                // 21: activity.v1.LuckySpinEventReq
	(*CheckUserRedPacketConditionReq)(nil),   // 22: activity.v1.CheckUserRedPacketConditionReq
	(*CheckUserRedPacketConditionReply)(nil), // 23: activity.v1.CheckUserRedPacketConditionReply
	(*IncreaseUserRedPacketCountReq)(nil),    // 24: activity.v1.IncreaseUserRedPacketCountReq
	nil,                                      // 25: activity.v1.LuckyPointsUsedItem.DetailEntry
	nil,                                      // 26: activity.v1.LuckyPointsAddItem.DetailEntry
	nil,                                      // 27: activity.v1.UseLuckyPointReq.DetailEntry
	nil,                                      // 28: activity.v1.AddLuckyValReq.DetailEntry
	nil,                                      // 29: activity.v1.CheckUserRedPacketConditionReply.UserPacketConditionsEntry
}
var file_proto_activity_v1_activity_proto_depIdxs = []int32{
	7,  // 0: activity.v1.RewardListReply.data:type_name -> activity.v1.RewardData
	1,  // 1: activity.v1.RewardData.spin_type:type_name -> activity.v1.SpinType
	1,  // 2: activity.v1.LuckyPointsUsedItem.spin_type:type_name -> activity.v1.SpinType
	14, // 3: activity.v1.LuckyPointsUsedItem.UsedList:type_name -> activity.v1.UseLuckyPoint
	25, // 4: activity.v1.LuckyPointsUsedItem.detail:type_name -> activity.v1.LuckyPointsUsedItem.DetailEntry
	10, // 5: activity.v1.LuckyPointsUsedListReply.data:type_name -> activity.v1.LuckyPointsUsedItem
	26, // 6: activity.v1.LuckyPointsAddItem.detail:type_name -> activity.v1.LuckyPointsAddItem.DetailEntry
	12, // 7: activity.v1.LuckyPointsAddListReply.data:type_name -> activity.v1.LuckyPointsAddItem
	1,  // 8: activity.v1.UseLuckyPointReq.spin_type:type_name -> activity.v1.SpinType
	27, // 9: activity.v1.UseLuckyPointReq.detail:type_name -> activity.v1.UseLuckyPointReq.DetailEntry
	17, // 10: activity.v1.GetLuckyPointReply.data:type_name -> activity.v1.GetLuckyPointItem
	28, // 11: activity.v1.AddLuckyValReq.detail:type_name -> activity.v1.AddLuckyValReq.DetailEntry
	0,  // 12: activity.v1.LuckySpinEventReq.type:type_name -> activity.v1.EventType
	29, // 13: activity.v1.CheckUserRedPacketConditionReply.user_packet_conditions:type_name -> activity.v1.CheckUserRedPacketConditionReply.UserPacketConditionsEntry
	20, // 14: activity.v1.LiveActivityInnerService.RedPacketCampaignEvent:input_type -> activity.v1.RedPacketCampaignEventReq
	22, // 15: activity.v1.LiveActivityInnerService.CheckUserRedPacketCondition:input_type -> activity.v1.CheckUserRedPacketConditionReq
	24, // 16: activity.v1.LiveActivityInnerService.IncreaseUserRedPacketCount:input_type -> activity.v1.IncreaseUserRedPacketCountReq
	21, // 17: activity.v1.LiveActivityInnerService.LuckySpinEvent:input_type -> activity.v1.LuckySpinEventReq
	19, // 18: activity.v1.LiveActivityInnerService.AddLuckyPoint:input_type -> activity.v1.AddLuckyValReq
	15, // 19: activity.v1.LiveActivityInnerService.UseLuckyPoint:input_type -> activity.v1.UseLuckyPointReq
	16, // 20: activity.v1.LiveActivityInnerService.GetUserLuckyPoint:input_type -> activity.v1.GetLuckyPointReq
	8,  // 21: activity.v1.LiveActivityInnerService.LuckyPointsAddList:input_type -> activity.v1.GetLuckyPointListReq
	8,  // 22: activity.v1.LiveActivityInnerService.LuckyPointsUsedList:input_type -> activity.v1.GetLuckyPointListReq
	9,  // 23: activity.v1.LiveActivityInnerService.RewardList:input_type -> activity.v1.RewardListReq
	4,  // 24: activity.v1.LiveActivityInnerService.GetUserInviteCount:input_type -> activity.v1.GetUserInviteCountReq
	3,  // 25: activity.v1.LiveActivityInnerService.RedPacketCampaignEvent:output_type -> activity.v1.ActivityReply
	23, // 26: activity.v1.LiveActivityInnerService.CheckUserRedPacketCondition:output_type -> activity.v1.CheckUserRedPacketConditionReply
	3,  // 27: activity.v1.LiveActivityInnerService.IncreaseUserRedPacketCount:output_type -> activity.v1.ActivityReply
	3,  // 28: activity.v1.LiveActivityInnerService.LuckySpinEvent:output_type -> activity.v1.ActivityReply
	3,  // 29: activity.v1.LiveActivityInnerService.AddLuckyPoint:output_type -> activity.v1.ActivityReply
	3,  // 30: activity.v1.LiveActivityInnerService.UseLuckyPoint:output_type -> activity.v1.ActivityReply
	18, // 31: activity.v1.LiveActivityInnerService.GetUserLuckyPoint:output_type -> activity.v1.GetLuckyPointReply
	13, // 32: activity.v1.LiveActivityInnerService.LuckyPointsAddList:output_type -> activity.v1.LuckyPointsAddListReply
	11, // 33: activity.v1.LiveActivityInnerService.LuckyPointsUsedList:output_type -> activity.v1.LuckyPointsUsedListReply
	6,  // 34: activity.v1.LiveActivityInnerService.RewardList:output_type -> activity.v1.RewardListReply
	5,  // 35: activity.v1.LiveActivityInnerService.GetUserInviteCount:output_type -> activity.v1.GetUserInviteCountReply
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_activity_v1_activity_proto_init() }
func file_proto_activity_v1_activity_proto_init() {
	if File_proto_activity_v1_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_activity_v1_activity_proto_rawDesc), len(file_proto_activity_v1_activity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_activity_v1_activity_proto_goTypes,
		DependencyIndexes: file_proto_activity_v1_activity_proto_depIdxs,
		EnumInfos:         file_proto_activity_v1_activity_proto_enumTypes,
		MessageInfos:      file_proto_activity_v1_activity_proto_msgTypes,
	}.Build()
	File_proto_activity_v1_activity_proto = out.File
	file_proto_activity_v1_activity_proto_goTypes = nil
	file_proto_activity_v1_activity_proto_depIdxs = nil
}
